### ISSUE TITLE
Unable to add to discord servers

### ISSUE THREAD

**Issue by u4dandy** [eartharoid/discord-media-helper#1]
When trying to add the bot to a server I get the following which points to the below link:

![image](https://github.com/eartharoid/discord-media-helper/assets/15972247/750fe3f9-5dae-4c00-9c5c-eb3c0ad077fd)

https://support.discord.com/hc/en-us/articles/360040720412-Bot-Verification-and-Data-Whitelisting

**Comment by eartharoid** [comment]
Sorry for the wait @u4dandy.
The Media-Helper application isn't managed by me so I can't do anything about this.
@rtcflyer runs it and I've let him know.

**Comment by RTCFlyer** [comment]
I've applied for verification so we're just waiting on discords end at the moment. Apologies for the wait, will provide an update once it's been verified.

**Comment by eartharoid** [comment]
@u4dandy the bot is now verified and can be added at https://discord.com/oauth2/authorize?client_id=1026547091121655808&permissions=274878032960&scope=bot%20applications.commands
