### ISSUE TITLE
Bot doesnt auto embed links.

### ISSUE THREAD

**Issue by sigglypuff** [eartharoid/discord-media-helper#10]
The description suggests its supposed to auto embed links but it doesn't seem to be working.

If i manually do it with an app command it works.

Looking to confirm if its a limitation of pre-established bot.

**Comment by eartharoid** [comment]
@sigglypuff what URLs have you tried?
URLs that are explicitly supported should be embedded automatically. When you use the app command the bot tries every URL, even ones it doesn't recognise, and some of those may work but are not guaranteed to.

**Comment by sigglypuff** [comment]
This is in regards to facebook, Whenever a facebook link is posted it only shows this:
![image](https://github.com/user-attachments/assets/e5f8a8fe-0c4a-4c9a-aecd-7a7bc5fa24d3)

Reels show this instead:
![image](https://github.com/user-attachments/assets/f720190e-28d6-482f-aadc-86ec57dab4f7)

If i force the app to embed media via clicking the triple dots on the posted link it will than generate it, It doesn't do this automatically only manually.

**Comment by sigglypuff** [comment]
Didn't mean to close it the issue report. Ignore that.
